[default.extend-identifiers]
BA = "BA"
Cleary = "Cleary"
compsite = "compsite"
epsiode = "epsiode"
FOM = "FOM"
NED = "NED"
SUite = "SUite"
Universite = "Universite"
varity = "varity"
Varity = "Varity"

[default.extend-words]
NED = "NED"
