query { 
  organization(login:"ORGNAME") {
    repositories(first:50 PGCURS) {
      nodes {
        nameWithOwner
        name
        owner {
          login
        }
        url
        stargazers {
          totalCount
        }
        forks {
          totalCount
        }
        homepageUrl
        description
        primaryLanguage {
          name
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}