query ($ownName: String!, $repoName: String!) {
  repository(owner: $ownName, name: $repoName) {
    nameWithOwner
    name
    owner {
      login
    }
    url
    homepageUrl
    description
    stargazers {
      totalCount
    }
    mentionableUsers {
      totalCount
    }
    forks {
      totalCount
    }
    primaryLanguage {
      name
    }
    languages {
      totalCount
    }
    repositoryTopics {
      totalCount
    }
  }
}
# {"ownName": "LLNL", "repoName": "llnl.github.io"}
