query ($ownName: String!, $repoName: String!) {
  repository(owner: $ownName, name: $repoName) {
    pullRequests_Open: pullRequests(states: OPEN) {
      totalCount
    }
    pullRequests_Closed: pullRequests(states: CLOSED) {
      totalCount
    }
    pullRequests_Merged: pullRequests(states: MERGED) {
      totalCount
    }
    issues_Open: issues(states: OPEN) {
      totalCount
    }
    issues_Closed: issues(states: CLOSED) {
      totalCount
    }
  }
}
# {"ownName": "LLNL", "repoName": "llnl.github.io"}
