query {
  repository(owner:"OWNNAME", name:"REPONAME") {
    repositoryTopics(first:50 PGCURS) {
      totalCount
      nodes {
        topic {
          name
        }
        resourcePath
        url
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}