query { 
  organization(login:"ORGNAME") {
  	name
    repositories(first:50 PGCURS) {
      totalCount
      nodes {
        nameWithOwner
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
  rateLimit {
    limit
    cost
    remaining
    resetAt
  }
}