query {
  repository(owner:"OWNNAME", name:"REPONAME") {
    languages(first:25 PGCURS) {
      totalCount
      nodes {
        name
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
  rateLimit {
    limit
    cost
    remaining
    resetAt
  }
}