query {
  repository(owner:"OWNNAME", name:"REPONAME") {
    labels(first:50 PGCURS) {
      totalCount
      nodes {
        name
        color
        issues {
          totalCount
        }
        pullRequests {
          totalCount
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}