query ($orgName: String!, $numRepos: Int!, $pgCursor: String) {
  organization(login: $orgName) {
    repositories(privacy: PUBLIC, first: $numRepos, after: $pgCursor) {
      nodes {
        nameWithOwner
        name
        owner {
          login
        }
        url
        stargazers {
          totalCount
        }
        forks {
          totalCount
        }
        homepageUrl
        description
        primaryLanguage {
          name
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
# {"orgName": "LLNL", "numRepos": 50, "pgCursor": null}
