query ($ownName: String!, $repoName: String!) {
  repository(owner: $ownName, name: $repoName) {
    licenseInfo {
      name
      nickname
      spdxId
      url
    }
  }
}
# {"ownName": "LLNL", "repoName": "llnl.github.io"}
